--------------------------------------------------------
--  File created - Wednesday-May-22-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GENRES
--------------------------------------------------------

  CREATE TABLE "SCOTT"."GENRES" 
   (	"GENRE_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.GENRES
SET DEFINE OFF;
Insert into SCOTT.GENRES (GENRE_ID,NAME) values (1,'Action');
Insert into SCOTT.GENRES (GENRE_ID,NAME) values (2,'Adventure');
Insert into SCOTT.GENRES (GENRE_ID,NAME) values (3,'Drama');
Insert into SCOTT.GENRES (GENRE_ID,NAME) values (4,'Comedy');
Insert into SCOTT.GENRES (GENRE_ID,NAME) values (5,'Sci-Fi');
--------------------------------------------------------
--  DDL for Index SYS_C0013255
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0013255" ON "SCOTT"."GENRES" ("GENRE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013256
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0013256" ON "SCOTT"."GENRES" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger GENRE_BEFORE_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."GENRE_BEFORE_INSERT" 
BEFORE INSERT ON Genres
FOR EACH ROW
BEGIN
    :new.genre_id := genre_seq.NEXTVAL;
END;

/
ALTER TRIGGER "SCOTT"."GENRE_BEFORE_INSERT" ENABLE;
--------------------------------------------------------
--  Constraints for Table GENRES
--------------------------------------------------------

  ALTER TABLE "SCOTT"."GENRES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GENRES" ADD PRIMARY KEY ("GENRE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."GENRES" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
