--------------------------------------------------------
--  File created - Wednesday-May-22-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REVIEWS
--------------------------------------------------------

  CREATE TABLE "SCOTT"."REVIEWS" 
   (	"REVIEW_ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0), 
	"MOVIE_ID" NUMBER(*,0), 
	"RATING" NUMBER(*,0), 
	"REVIEW" CLOB COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("REVIEW") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into SCOTT.REVIEWS
SET DEFINE OFF;
Insert into SCOTT.REVIEWS (REVIEW_ID,USER_ID,MOVIE_ID,RATING,CREATED_AT) values (81,1,1,5,to_timestamp('24-05-22 22:57:03.107423000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.REVIEWS (REVIEW_ID,USER_ID,MOVIE_ID,RATING,CREATED_AT) values (82,2,2,4,to_timestamp('24-05-22 22:57:03.141914000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.REVIEWS (REVIEW_ID,USER_ID,MOVIE_ID,RATING,CREATED_AT) values (83,3,3,5,to_timestamp('24-05-22 22:57:03.146774000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.REVIEWS (REVIEW_ID,USER_ID,MOVIE_ID,RATING,CREATED_AT) values (84,4,4,5,to_timestamp('24-05-22 22:57:03.151372000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.REVIEWS (REVIEW_ID,USER_ID,MOVIE_ID,RATING,CREATED_AT) values (85,5,5,4,to_timestamp('24-05-22 22:57:03.155918000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.REVIEWS (REVIEW_ID,USER_ID,MOVIE_ID,RATING,CREATED_AT) values (86,6,6,4,to_timestamp('24-05-22 22:57:03.160714000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.REVIEWS (REVIEW_ID,USER_ID,MOVIE_ID,RATING,CREATED_AT) values (87,7,7,5,to_timestamp('24-05-22 22:57:03.165787000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.REVIEWS (REVIEW_ID,USER_ID,MOVIE_ID,RATING,CREATED_AT) values (88,8,8,5,to_timestamp('24-05-22 22:57:03.170798000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.REVIEWS (REVIEW_ID,USER_ID,MOVIE_ID,RATING,CREATED_AT) values (89,9,9,4,to_timestamp('24-05-22 22:57:03.175329000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.REVIEWS (REVIEW_ID,USER_ID,MOVIE_ID,RATING,CREATED_AT) values (90,10,10,5,to_timestamp('24-05-22 22:57:03.180436000','RR-MM-DD HH24:MI:SSXFF'));
--------------------------------------------------------
--  DDL for Index SYS_C0013264
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0013264" ON "SCOTT"."REVIEWS" ("REVIEW_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger REVIEW_BEFORE_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."REVIEW_BEFORE_INSERT" 
BEFORE INSERT ON Reviews
FOR EACH ROW
BEGIN
    :new.review_id := review_seq.NEXTVAL;
END;

/
ALTER TRIGGER "SCOTT"."REVIEW_BEFORE_INSERT" ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEWS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."REVIEWS" ADD CHECK (rating BETWEEN 1 AND 5) ENABLE;
  ALTER TABLE "SCOTT"."REVIEWS" ADD PRIMARY KEY ("REVIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEWS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."REVIEWS" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "SCOTT"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "SCOTT"."REVIEWS" ADD FOREIGN KEY ("MOVIE_ID")
	  REFERENCES "SCOTT"."MOVIES" ("MOVIE_ID") ENABLE;
