--------------------------------------------------------
--  File created - Wednesday-May-22-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SCOTT"."USERS" 
   (	"USER_ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"PASSWORD" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SCOTT.USERS
SET DEFINE OFF;
Insert into SCOTT.USERS (USER_ID,USERNAME,PASSWORD,EMAIL,CREATED_AT) values (1,'john_doe','password123','john@example.com',to_timestamp('24-05-21 21:10:49.349255000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.USERS (USER_ID,USERNAME,PASSWORD,EMAIL,CREATED_AT) values (2,'jane_doe','password456','jane@example.com',to_timestamp('24-05-21 21:12:43.767709000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.USERS (USER_ID,USERNAME,PASSWORD,EMAIL,CREATED_AT) values (3,'alice_smith','password789','alice@example.com',to_timestamp('24-05-21 21:12:43.772737000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.USERS (USER_ID,USERNAME,PASSWORD,EMAIL,CREATED_AT) values (4,'bob_brown','password012','bob@example.com',to_timestamp('24-05-21 21:12:43.776834000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.USERS (USER_ID,USERNAME,PASSWORD,EMAIL,CREATED_AT) values (5,'charlie_johnson','password345','charlie@example.com',to_timestamp('24-05-21 21:12:43.780602000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.USERS (USER_ID,USERNAME,PASSWORD,EMAIL,CREATED_AT) values (6,'dana_white','password678','dana@example.com',to_timestamp('24-05-21 21:12:43.784832000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.USERS (USER_ID,USERNAME,PASSWORD,EMAIL,CREATED_AT) values (7,'eve_green','password901','eve@example.com',to_timestamp('24-05-21 21:12:43.789541000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.USERS (USER_ID,USERNAME,PASSWORD,EMAIL,CREATED_AT) values (8,'frank_black','password234','frank@example.com',to_timestamp('24-05-21 21:12:43.794000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.USERS (USER_ID,USERNAME,PASSWORD,EMAIL,CREATED_AT) values (9,'grace_blue','password567','grace@example.com',to_timestamp('24-05-21 21:12:43.798645000','RR-MM-DD HH24:MI:SSXFF'));
Insert into SCOTT.USERS (USER_ID,USERNAME,PASSWORD,EMAIL,CREATED_AT) values (10,'harry_yellow','password890','harry@example.com',to_timestamp('24-05-21 21:12:43.803423000','RR-MM-DD HH24:MI:SSXFF'));
--------------------------------------------------------
--  DDL for Index SYS_C0013251
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0013251" ON "SCOTT"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013252
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0013252" ON "SCOTT"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013253
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0013253" ON "SCOTT"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger USER_BEFORE_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCOTT"."USER_BEFORE_INSERT" 
BEFORE INSERT ON Users
FOR EACH ROW
BEGIN
    :new.user_id := user_seq.NEXTVAL;
END;
/
ALTER TRIGGER "SCOTT"."USER_BEFORE_INSERT" ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SCOTT"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."USERS" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."USERS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
